# Generated by Django 4.1.7 on 2023-08-22 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Communitys",
            fields=[
                ("id_group", models.BigAutoField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=150)),
                ("anggota_group", models.IntegerField(default=1)),
                (
                    "deskripsi_group",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("tanggal_dibuat", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.communitys",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
