# Generated by Django 4.1.7 on 2023-08-22 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="members",
            name="member",
        ),
        migrations.AddField(
            model_name="members",
            name="member",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
