# Generated by Django 4.1.7 on 2023-08-22 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0002_remove_members_member_members_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="members",
            name="member",
        ),
        migrations.AddField(
            model_name="members",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
