# Generated by Django 4.1.7 on 2023-08-22 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0005_group_groupmember_remove_members_id_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="createdfrom",
            field=models.DateField(
                auto_created=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="groupmember",
            name="joins",
            field=models.DateField(
                auto_created=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="groupmember",
            name="premission",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="group",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="community.group"
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="member",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
