# Generated by Django 4.1.7 on 2023-08-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0006_group_createdfrom_groupmember_joins_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmember",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="community.group"
            ),
        ),
    ]
