# Generated by Django 4.1.7 on 2023-08-22 14:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0007_alter_groupmember_group"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupmember",
            unique_together={("group", "member")},
        ),
    ]
