# Generated by Django 4.1.7 on 2023-08-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0009_alter_groupmember_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupmember",
            name="premission",
        ),
        migrations.AddField(
            model_name="groupmember",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Members", "Members"), ("Admin", "admin")],
                max_length=10,
                null=True,
            ),
        ),
    ]
