# Generated by Django 4.1.7 on 2023-08-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0010_remove_groupmember_premission_groupmember_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmember",
            name="status",
            field=models.CharField(
                choices=[("Members", "Members"), ("Admin", "admin")], max_length=10
            ),
        ),
    ]
