# Generated by Django 4.1.7 on 2023-08-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0012_pesangroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="PesanDiGrup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.group",
                    ),
                ),
                (
                    "pengirim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.pesangroup",
                    ),
                ),
            ],
        ),
    ]
