# Generated by Django 4.1.7 on 2023-08-28 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0013_pesandigrup"),
    ]

    operations = [
        migrations.CreateModel(
            name="PesanGrup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_pesan", models.TextField()),
                ("kirim", models.DateTimeField(auto_now_add=True)),
                (
                    "grup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.group",
                    ),
                ),
                (
                    "pengirim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="pesangroup",
            name="pengirim",
        ),
        migrations.DeleteModel(
            name="PesanDiGrup",
        ),
        migrations.DeleteModel(
            name="PesanGroup",
        ),
    ]
